spring.application.name=ms-producto
server.port=8086

spring.datasource.url=jdbc:mysql://localhost:3306/db_producto
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

spring.security.user.name=admin
spring.security.user.password=admin123

ms.categoria.url=http://localhost:8085
ms.categoria.user=admin
ms.categoria.password=admin123