spring.application.name=ms-rol
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/db_ecotienda
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

spring.security.user.name=admin
spring.security.user.password=admin123

ms.permiso.url=http://localhost:8081

ms.permiso.user=admin
ms.permiso.password=admin123

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html